### ISSUE TITLE
Consider using Ripgrep instead of sliver search

### ISSUE THREAD

**Issue by weihanglo** [litaxc/dotfiles#1]
In my opinion, [Ripgrep](https://github.com/BurntSushi/ripgrep) may be one of the best search tool. Microsoft's open source project Visual Studio Code has also [integrated Ripgrep in its search engine](https://github.com/Microsoft/vscode/pull/22722). You may check [this post](http://blog.burntsushi.net/ripgrep/) out. It does some awesome benchmarks and explains a lot.

**Comment by litaxc** [comment]
Will definitely give it a shot, thanks for your suggestion and resources @weihanglo .
